apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{.Values.msName}}
    chart: {{.Chart.Name}}-{{.Chart.Version}}
  name: {{.Values.msName}}
data:
  envoy_config.yaml: |
{{.Files.Get "envoy_config.yaml" | indent 4}}
